In [1]:
import numpy as np

In [2]:
# VECTOR
twoDimExample = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [3]:
twoDimExample.ndim

2

In [4]:
#Numpy Array Arithmetic Operations ---- ALL OPERATIONS ARE ELEMENT-WISE

#Addition Operation ----- Elementwise Addition
twoDimExample + twoDimExample


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
#Subtraction Operation ----- Elementwise Subtraction
twoDimExample - twoDimExample

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
#Multiplication Operation ----- Elementwise Multiplication
twoDimExample * twoDimExample

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
mat1 = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
mat1 * mat1

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [13]:
#Matrix Multiplication ------ Hadamard Multiplication
np.matmul(twoDimExample, twoDimExample)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#BROADCASTING OPERATION

twoDimExample * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
twoDimStringExample = np.array([
    ['a','b','c'],
    ['d','e','f'],
    ['g','h','i']
])

In [16]:
type(twoDimExample)

numpy.ndarray

In [17]:
type(mat1)

numpy.matrix

In [ ]:
#Linear Systems

In [18]:
import pandas as pd
import numpy as np

In [19]:
data = pd.read_csv('Salary_Data.csv')

In [20]:
# Seperate data as features and label
features = data.iloc[:,[0]].values
label = data.iloc[:, [1]].values

In [21]:

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(features,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=10)

In [22]:
from sklearn.linear_model import LinearRegression
trainedModel = LinearRegression()
trainedModel.fit(X_train,y_train)

LinearRegression()

In [23]:
trainedModel.coef_

array([[9356.86299354]])

In [24]:
trainedModel.intercept_

array([26089.09663242])

In [ ]:
#sal = (9356.86299354 * yExp) + 26089.09663242

In [25]:
A = np.concatenate([X_train , np.ones(len(X_train)).reshape(-1,1)] , axis = 1)

In [26]:
A

array([[ 4.1,  1. ],
       [ 9.6,  1. ],
       [ 4. ,  1. ],
       [ 1.3,  1. ],
       [ 6. ,  1. ],
       [ 4.5,  1. ],
       [ 5.9,  1. ],
       [ 3. ,  1. ],
       [ 4. ,  1. ],
       [ 8.2,  1. ],
       [ 8.7,  1. ],
       [10.3,  1. ],
       [ 7.9,  1. ],
       [ 3.9,  1. ],
       [ 9.5,  1. ],
       [10.5,  1. ],
       [ 3.2,  1. ],
       [ 9. ,  1. ],
       [ 5.1,  1. ],
       [ 5.3,  1. ],
       [ 1.1,  1. ],
       [ 4.9,  1. ],
       [ 2.2,  1. ],
       [ 3.7,  1. ]])

In [29]:
from scipy import linalg
#Least Squares

myModel = linalg.lstsq(A,y_train)[0]

In [32]:
myModel

array([[ 9356.86299354],
       [26089.09663242]])

In [ ]:
#sal = (9356.86299354 * yExp) + 26089.09663242

In [37]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]

oneDimArray = np.array([list1,list2])

oneDimArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
oneDimArray.ndim

2

In [39]:
oneDimArray = np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
oneDimArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#numpy and pandas
# arr1[rowRange , colRange]
# arr1[rowList, colList]

# rowRange---- startIndex : endIndex + 1
# colRange---- startIndex : endIndex + 1

In [45]:
test = np.random.randint(1,101,100).reshape(10,10)
test

array([[ 67,  12,  26,  39,  16,   6,  66,  58,  46,  17],
       [ 35,  49,  18,  16,  28,  81,  66,  71,  70,  75],
       [ 52,  60,  81,  36,  56,  83,  13,  19,  81,  34],
       [ 76,  99,  20,  49,  38,  62,  98,  27,  85,  38],
       [ 35,  10,  37,  96,  97,  84,  95,  73,  95,  38],
       [ 26,  10,  60,  70, 100,  91,  63,  98,  32,   1],
       [ 38,   7,  82,  66,  98,  93,  98,  54,  79,  30],
       [  8,  85,  93,  49,  73,  80,  92,   7,  88,  40],
       [ 39,  57,   2,   7,  11,  23,  59,  72,  17,  94],
       [  5,  48,  89,  61,  13,   6,  44,   9,   7,  23]])

In [56]:
test[[0,1,2],[1,2]]

IndexError: ignored

In [50]:
test[0:2,:]

array([[67, 12, 26, 39, 16,  6, 66, 58, 46, 17],
       [35, 49, 18, 16, 28, 81, 66, 71, 70, 75]])

In [52]:
np.random.randint(1,101,100).reshape(10,10)

array([[88, 14,  4, 54, 71,  1, 47, 91, 26, 34],
       [40, 79, 82, 37, 75, 16, 84,  2, 51, 74],
       [84, 42, 62,  8,  3,  8, 85,  8, 39, 67],
       [67, 26, 30, 97, 43, 30, 43, 62, 37, 57],
       [62, 88, 71, 29, 20, 53, 96, 57, 44, 44],
       [26, 51, 79, 79,  9, 55, 81, 78, 42, 53],
       [41, 85, 25, 68, 60,  2, 42, 23, 57,  2],
       [89, 86, 34, 90, 44, 46,  7, 72, 84, 40],
       [85, 11,  3, 92, 39, 38, 97, 46, 73, 35],
       [75, 55, 56, 41, 56, 21, 14, 12, 61, 60]])

In [55]:
np.random.randint(1,101,100).reshape(100,1)

array([[ 71],
       [ 39],
       [ 98],
       [ 34],
       [ 94],
       [ 93],
       [ 79],
       [ 60],
       [ 70],
       [ 92],
       [ 85],
       [ 14],
       [ 81],
       [ 15],
       [ 54],
       [ 75],
       [ 86],
       [ 24],
       [ 60],
       [ 19],
       [ 54],
       [ 20],
       [ 29],
       [ 53],
       [ 26],
       [ 82],
       [ 70],
       [  2],
       [ 55],
       [ 32],
       [ 98],
       [ 62],
       [ 83],
       [ 84],
       [ 78],
       [ 47],
       [ 99],
       [ 16],
       [ 94],
       [ 12],
       [ 33],
       [ 17],
       [ 33],
       [ 37],
       [ 25],
       [ 33],
       [ 81],
       [ 30],
       [ 64],
       [ 17],
       [  6],
       [ 60],
       [100],
       [  4],
       [ 22],
       [ 33],
       [ 51],
       [ 31],
       [ 37],
       [ 49],
       [ 88],
       [ 13],
       [  7],
       [ 75],
       [ 69],
       [ 65],
       [ 50],
       [ 57],
       [ 18],
       [ 65],
       [ 70],
      